# Generated by Django 5.1.5 on 2025-01-14 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CelOszczednosciowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kwota_docelowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obecna_kwota', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miesiac', models.DateField()),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_aplikacji.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Powiadomienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('przeczytane', models.BooleanField(default=False)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_budzetu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transakcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('przychod', 'Przychód'), ('wydatek', 'Wydatek')], max_length=10)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('opis', models.TextField(blank=True, null=True)),
                ('kategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='folder_aplikacji.kategoria')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
